import type { Metadata } from "next";
import Link from "next/link";
import { requireOrgContext } from "@/server/authz/context";
import { listNotifications } from "@/features/notifications/server/service";
import { markAllNotificationsReadAction } from "@/features/notifications/actions";
import { ActionButton } from "@/components/app/actions";
import { EmptyState, FilterLink, PageHeader, TimeAgo } from "@/components/app/primitives";
import { NotificationLink } from "@/features/notifications/components/notification-link";
import { cn } from "@/lib/utils";

export const metadata: Metadata = { title: "Notifications" };

export default async function NotificationsPage({
  params,
  searchParams,
}: PageProps<"/org/[orgSlug]/notifications">) {
  const { orgSlug } = await params;
  const sp = await searchParams;
  const ctx = await requireOrgContext(orgSlug);
  const unreadOnly = sp.unread === "1";
  const before = typeof sp.before === "string" ? sp.before : null;
  const { items, hasMore } = await listNotifications(ctx, { limit: 50, unreadOnly, before });
  const base = `/org/${ctx.org.slug}/notifications`;

  return (
    <div className="mx-auto max-w-[900px]">
      <PageHeader
        title="Notifications"
        description="Assignments, reviews, and due or expiring items. Generated by actions in this workspace and by the scheduled compliance scan."
        actions={
          <ActionButton
            size="sm"
            action={markAllNotificationsReadAction.bind(null, ctx.org.slug)}
            success="All notifications marked as read"
          >
            Mark all read
          </ActionButton>
        }
      />
      <div className="mb-3 flex gap-1.5">
        <FilterLink href={base} active={!unreadOnly}>
          All
        </FilterLink>
        <FilterLink href={`${base}?unread=1`} active={unreadOnly}>
          Unread
        </FilterLink>
      </div>
      {items.length === 0 ? (
        <EmptyState
          title={unreadOnly ? "You are all caught up" : "No notifications yet"}
          description="You will be notified when work is assigned to you, evidence is reviewed, or something you own becomes due."
        />
      ) : (
        <ul className="border-border rounded-md border">
          {items.map((n) => (
            <li key={n.id} className="border-border border-b last:border-0">
              <NotificationLink
                orgSlug={ctx.org.slug}
                id={n.id}
                href={n.linkPath}
                unread={!n.readAt}
              >
                <span
                  className={cn(
                    "mt-1.5 size-1.5 shrink-0 rounded-full",
                    n.readAt ? "bg-transparent" : "bg-accent",
                  )}
                  aria-hidden
                />
                <span className="min-w-0 flex-1">
                  <span className={cn("block text-[13px]", !n.readAt && "font-medium")}>
                    {n.title}
                  </span>
                  {n.body ? (
                    <span className="text-muted-foreground mt-0.5 block text-xs">{n.body}</span>
                  ) : null}
                </span>
                <span className="text-muted-foreground text-xs whitespace-nowrap">
                  <TimeAgo date={n.createdAt} timeZone={ctx.org.timezone} />
                </span>
              </NotificationLink>
            </li>
          ))}
        </ul>
      )}
      {hasMore && items.length > 0 ? (
        <div className="mt-3">
          <Link
            href={`${base}?${new URLSearchParams({ ...(unreadOnly ? { unread: "1" } : {}), before: items.at(-1)!.id }).toString()}`}
            className="text-accent text-[13px] hover:underline"
          >
            Older notifications
          </Link>
        </div>
      ) : null}
    </div>
  );
}
